#include "gpexport.hpp"

#include <cstdio>
#include <string>

#include "palette.hpp"
#include "save.hpp"

namespace ech {
namespace {

// The SAME ramp the app draws with, from palette.hpp. Two colour tables would
// mean an exported figure that is a different figure.
std::string series_hex(std::size_t i, std::size_t n) {
    const Rgb c = series_colour(i, n);
    char b[16];
    std::snprintf(b, sizeof b, "#%02x%02x%02x", c.r, c.g, c.b);
    return b;
}
constexpr const char* kInk = "#1a1a1a";
constexpr const char* kDim = "#6d6d6d";
constexpr const char* kLine = "#d7d7d7";

std::string esc(std::string_view s) {
    std::string o;
    o.reserve(s.size());
    for (char c : s) {
        if (c == '"' || c == '\\') o += '\\';
        o += c;
    }
    return o;
}

// Through write_atomic, like the session file. An export is a set of files
// that only mean anything together -- a .gp naming three .dat files, a CSV of
// the same numbers -- and a run that dies partway used to leave a new script
// pointing at last time's data, which reruns and draws the wrong figure
// without complaining.
bool write_text(const std::string& path, const std::string& body,
                std::string& err) {
    return write_atomic(path, body, err);
}

std::string fmt(double v) {
    char buf[40];
    std::snprintf(buf, sizeof buf, "%.10g", v);
    return buf;
}

std::string basename_of(const std::string& p) {
    const std::size_t s = p.find_last_of("/\\");
    return s == std::string::npos ? p : p.substr(s + 1);
}

const char* kind_style(Kind k) {
    switch (k) {
        case Kind::Line: return "with lines lw 2";
        case Kind::Hist:
        case Kind::Bars: return "with boxes";
        case Kind::Scatter: break;
    }
    return "with points pt 7 ps 1.2";
}

}  // namespace

ExportResult write_gnuplot(const std::string& out_stem, const Table& t,
                           const Spec& s, const std::vector<Series>& series,
                           const Fit* fit) {
    ExportResult r;
    if (series.empty()) { r.error = "nothing to export"; return r; }
    const std::string stem = basename_of(out_stem);

    // THE SIDECAR MUST NOT EAT THE INPUT. The numbers go to <stem>.csv, and
    // when that resolves to the file being plotted the name changes instead.
    // Writing the plotted values over a 29 MB source file is a thing that has
    // happened here, and nothing in the output said so.
    std::string csv_path = out_stem + ".csv";
    if (csv_path == t.path()) csv_path = out_stem + ".figure.csv";

    std::string script;
    script.reserve(2048);
    script += "# generated by Echelle -- rerun with: gnuplot " + stem + ".gp\n";
    script += "set output '" + stem + ".svg'\n";
    // No background: the SVG is transparent and takes the colour of whatever
    // shows it. A baked-in panel fill is a grey rectangle on a white page.
    script += "set terminal svg size 940,520 font 'Helvetica,10'\n";
    script += std::string("set border 3 lc rgb '") + kLine + "' lw 1\n";
    script += std::string("set tics nomirror out scale 0.6 tc rgb '") + kDim + "'\n";

    // A key is a guide to several things. One series has nothing to tell
    // apart and its entry only repeats the y label.
    const bool key = series.size() > 1 || fit != nullptr;
    script += key ? std::string("set key outside right top vertical Left reverse "
                                "samplen 1.2 spacing 1.3 textcolor rgb '") + kDim + "'\n"
                  : std::string("unset key\n");

    const std::string title = s.title.empty()
        ? (s.kind == Kind::Hist ? "distribution of " + s.x
                                : (s.y.empty() ? s.x : s.y[0]) + " vs " + s.x)
        : s.title;
    script += "set title \"" + esc(title) + "\" tc rgb '" + kInk +
              "' font 'Helvetica,12'\n";
    script += "set xlabel \"" + esc(s.x) + "\" tc rgb '" + kInk + "'\n";
    script += "set ylabel \"" +
              esc(s.kind == Kind::Hist ? "count" : (s.y.empty() ? "" : s.y[0])) +
              "\" tc rgb '" + kInk + "'\n";
    if (s.logx) script += "set logscale x\n";
    if (s.logy) script += "set logscale y\n";
    if (s.kind == Kind::Hist || s.kind == Kind::Bars)
        script += "set style fill solid 0.9 noborder\n";

    // Data goes to files, never inline. Inline data ('-') cannot be replotted
    // without the script, and the point of keeping the script is that the
    // inputs stay legible.
    std::string csv = "figure,series,x,value\n";
    std::string plot = "plot ";
    std::size_t n = 0;
    for (std::size_t i = 0; i < series.size(); ++i) {
        const Series& ser = series[i];
        const std::string dat = stem + ".d" + std::to_string(i + 1) + ".dat";
        std::string body;
        body.reserve(ser.xs.size() * 24);
        for (std::size_t k = 0; k < ser.xs.size(); ++k) {
            body += fmt(ser.xs[k]);
            body += ' ';
            body += fmt(ser.ys[k]);
            body += '\n';
            csv += stem + "," + ser.label + "," + fmt(ser.xs[k]) + "," +
                   fmt(ser.ys[k]) + "\n";
        }
        n += ser.xs.size();
        const std::string dir =
            out_stem.substr(0, out_stem.size() - stem.size());
        if (!write_text(dir + dat, body, r.error)) return r;
        r.written.push_back(dir + dat);
        if (i) plot += ", \\\n     ";
        plot += "'" + dat + "' using 1:2 " + kind_style(s.kind) + " lc rgb '" +
                series_hex(i, series.size()) + "' title '" + ser.label + "'";
    }

    if (fit && fit->ok) {
        std::vector<double> cx, cy;
        curve(*fit, fit->x_lo, fit->x_hi, 200, cx, cy);
        const std::string dat = stem + ".fit.dat";
        std::string body;
        for (std::size_t k = 0; k < cx.size(); ++k)
            body += fmt(cx[k]) + " " + fmt(cy[k]) + "\n";
        const std::string dir = out_stem.substr(0, out_stem.size() - stem.size());
        if (!write_text(dir + dat, body, r.error)) return r;
        r.written.push_back(dir + dat);
        plot += ", \\\n     '" + dat + "' using 1:2 with lines lw 2 lc rgb '" +
                kInk + "' title 'fit'";
    }
    script += plot + "\n";

    const std::string dir = out_stem.substr(0, out_stem.size() - stem.size());
    if (!write_text(out_stem + ".gp", script, r.error)) return r;
    r.written.push_back(out_stem + ".gp");
    if (!write_text(csv_path, csv, r.error)) return r;
    r.written.push_back(csv_path);

    std::string cap = title + ". " + std::to_string(n) + " point(s) over " +
                      std::to_string(series.size()) + " series from `" +
                      basename_of(t.path()) + "`, filter `" +
                      (s.where.empty() ? "none" : s.where) + "`";
    if (t.n_excluded())
        cap += ", " + std::to_string(t.n_excluded()) + " row(s) excluded";
    cap += ". Drawn by Echelle from the declaration `" + spec_text(s) +
           "`; the CSV beside this file holds the plotted values and the .gp "
           "redraws it with gnuplot.\n";
    if (!write_text(out_stem + ".caption.md", cap, r.error)) return r;
    r.written.push_back(out_stem + ".caption.md");
    (void)dir;
    r.ok = true;
    return r;
}

}  // namespace ech
